[package]
name = "pss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
indicatif = "0.16.2"
oss-rust-sdk = "0.5.0"
